### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Tzg-AHU** [kotarot/rectangle-packing-solver#26]
Why is the result different every time?

**Comment by kotarot** [comment]
Hi @Tzg-AHU,
Because the solver is based on a random huristic algorithm. As a workaround, you could set a random seed to fix solutions like this:

```python
import rectangle_packing_solver as rps
import random
random.seed(12345)

problem = rps.Problem( your problem )

fixed_solution = rps.Solver().solve(problem)
```

I am thinking of adding an option to set the random seed to the `solve` method in the future.

**Comment by Tzg-AHU** [comment]
Thanks for your reply

**Comment by Tzg-AHU** [comment]
Excuse me,
  in solve.py, simanneal_minutes and simanneal_steps，What does that mean?How should the parameters be set？

**Comment by kotarot** [comment]
`simanneal_minutes` means how long the optimization process will go on. For example, if you set `simanneal_minutes=1.0`, the solving time will be roughly one minute. A longer process time might result in better solution. The default value is `0.1`. If you want to get a better solution, it's worth setting a larger value.

`simanneal_steps` is the number of steps for profiling the internal optimization parameters. The default value is 100, and for most of the cases, you don't need to change this value.

For more details, please refer to the simanneal library documantations. (My solver depends on this annealing optimization.)
https://github.com/perrygeo/simanneal

**Comment by Tzg-AHU** [comment]
I've learned,thanks a lot for your answer！
