### ISSUE TITLE
Run 20 blocks SA with different results

### ISSUE THREAD

**Issue by geniuscare247** [kotarot/rectangle-packing-solver#27]
Hi KOATAROT-san,

I ran example_large.py with the same script.
And trying find the solution with the limit.
for example, height_limit of solver is set 50, 
but finally I got a sparse floorplan, rather than a tight design in your example picture (floorplan_large_limit.png). 

is there any parameter need to be set for solver in large scale? I try small number of block, and the results looks normal.

**Comment by kotarot** [comment]
Hi @geniuscare247, thank you for the question.

I can also reproduce the problem you mentioned. The problem started to occur after fixing another recent issue (#23). This regression comes in version 0.0.4 (latest). So the work-around is: please use version 0.0.3 and run `example_large.py`. I'll soon start fixing the problem in the newer version.

Thank you for reporting the issue!

**Comment by kotarot** [comment]
Hi @geniuscare247, the new version `0.0.5` is released and this problem has been resolved. Please try it out. Thanks!

https://pypi.org/project/rectangle-packing-solver/

**Comment by kotarot** [comment]
The issue has been resolved in the latest version, I'll close this issue. Thank you again!

**Comment by geniuscare247** [comment]
Thank you very much !

It did solve the issue.
